"""empty message

Revision ID: 31539ed494cd
Revises: f81b32430d13
Create Date: 2019-01-10 23:34:48.815943

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from src.models.types.user_type import UserType

# revision identifiers, used by Alembic.
revision = '31539ed494cd'
down_revision = 'f81b32430d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('token', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column(
        'user_type', sqlalchemy_utils.types.choice.ChoiceType(UserType, impl=sa.Integer()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'token')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
