"""empty message
Revision ID: 6a55ac054078
Revises: 9c1b6121edf7
Create Date: 2019-02-21 17:23:53.429041
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a55ac054078'
down_revision = '9c1b6121edf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('rank', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'rank')
    # ### end Alembic commands ###